class Constants:
    EVENT_KIND_NOTE = 0
    EVENT_KIND_HOLD = 1
    EVENT_KIND_LARGE_SPINNER = 2
    EVENT_KIND_LARGE_SPINNER_LEFT = 3
    EVENT_KIND_LARGE_SPINNER_RIGHT = 4
    EVENT_KIND_SMALL_SPINNER = 5
    EVENT_KIND_SMALL_SPINNER_LEFT = 6
    EVENT_KIND_SMALL_SPINNER_RIGHT = 7

    EVENT_KIND_MEASURE_MARKER = 11
    EVENT_KIND_BEAT_MARKER = 12

    EVENT_KIND_GRAFICA_SECTION_START = 14
    EVENT_KIND_GRAFICA_SECTION_END = 15
